### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by kingreym** [UnionSelection/auction.dev#6]
<p>Uztaisīt registration sadaļu</p>

**Comment by Karliszars** [comment]
Title, valsti un dzimumu vajag (piem sutot papira vestules (ja sai sabiedribas dalai tas strada veljoprojam) ka uzrunat Mr vai Mrs??). bet ne vairak lai nav par smagu, skat optimalo viduscelu no siem abiem linkiem.
https://www.christies.com/mychristies/login.aspx
https://www.sothebys.com/en/registration/register-new-account.html

Christies ir labs nosaukums sim Basic account – Account for NON-TRANSACTIONAL ACTIVITIES. 

Ka atjaunot paroli ja aizmirsta (vai nekezam logu ar siem sikumiem?)
